### ISSUE TITLE
-v/VOLUME inconsistencies

### ISSUE THREAD

**Issue by krainboltgreene** [boot2docker/boot2docker#1021]
Okay, so up front this setup works:

``` docker
FROM ruby:2.2.2

ENV SOURCE "/usr/src/app"

WORKDIR $SOURCE
```

``` yaml
web:
  command: /usr/bin/foreman start
  build: .
  volumes:
    - .:/usr/src/app
  ports:
   - "3000:3000"
```

However, I started to realize that I wanted to push more things into docker: `bower install`, `npm install`, `bundle install`, and `rake db:setup`.

However these things require files to exist on the docker container before they're run! For `bower`, `npm`, and `bundle` it was easy: just use `COPY Gemfile $SOURCE/Gemfile` and things get copied over correctly. **I want to reiterate, `COPY source destination` works as intended.**

This "solution" doesn't work for `rake` tasks however, since the entire rails stack has to be present. Further more `COPY` is a build operation, meaning that changes to my (say) `config/application.rb` don't get pulled over, I need to rebuild to get the new source. So I decided to move my volume declaration out of `docker-compose.yml` and into `Dockerfile`. I couldn't get it to behave!

For reference, this does not seem to work:

``` docker
FROM ruby:2.2.2

ENV SOURCE "/usr/src/app"

WORKDIR $SOURCE
VOLUME .:$SOURCE
```

``` yaml
web:
  command: /usr/bin/foreman start
  build: .
  ports:
   - "3000:3000"
```

The resulting container creates a `/usr/src/app` but it's empty.

This is strange to me since `-v` and `VOLUME` are supposed to be the same (according to docker documentation).

Now I realize why this might be a complication with `boot2docker` being a layer between my filesystem and the containers. Since b2d mounts my `/Users` directory however I figured it would work fine.

Why the discrepancy? How do I fix it? If I can't use `.` as a source, how do I source while being idiomatic and not forcing other developers to overwrite their source?
