### ISSUE TITLE
Windows - Volumes Permissions

### ISSUE THREAD

**Issue by belthaZornv** [boot2docker/boot2docker#1128]
I have boot2docker installed, and a docker-compose file with the following:

```

mysql:
    image: mysql
    ports: 
        - "6603:3306"    
    environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_USER: mysql
fpm:
    image: php:7.0.2-fpm
    volumes:
        - /c/Users/Administrator/www:/var/www/html
    ports:
        - "9000:9000"
    links:
        - mysql
nginx:
    image: nginx 
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /c/Users/Administrator/www:/var/www/html
    links:
        - fpm
```

I can go to the ip and see the nginx welcome page which is fine; although when I try mkdir (PHP) or something that creates a file I get permission denied. - I found an issue regarding Mac OS having the same issue and I tried a lot of ways to go around it; but I cannot find a good working example I can work up on and learn from. 

If anyone has this issue can they share how they fixed it?
