### ISSUE TITLE
[Feature Request] - boot2docker shared host volume for development

### ISSUE THREAD

**Issue by blaggacao** [boot2docker/boot2docker#1145]
@SvenDowideit 

As this has been an issue long around for many, I think there is an opportunity to get this solved...
As stated on the corresponding docker-machine issue [here](https://github.com/docker/machine/issues/179#issuecomment-190367805), there is a cifs/nfs volume share plugin available. However I have difficulties to get it working on boot2docker and it is not persisted. So this consists in an request to include https://github.com/gondor/docker-volume-netshare into boot2docker natively and make this the standard way (via docs) of sharing volumes on hypervisors (not just virtualbox).

A docker-compose.yaml then just looks something like this:

```
volumes:
    src:
        driver: nfs
        driver_opts:
            name: 192.168.0.66/flct
```
What do you think?
