### ISSUE TITLE
Cache response

### ISSUE THREAD

**Issue by baptistedonaux** [boot2docker/boot2docker#705]
I have a strange comportement with boot2docker for mac. I use a simple nginx from the official image. Nginx responds a simple HTML, but when I change the file content, the nginx response doesn't change. No browser cache, or Nginx cache. I must reboot boot2docker to update the content delivery.

My Fig configuration is this :

``` yml
front:
    image: nginx:1.7
    volumes:
        - .:/usr/share/nginx/html:rw
    ports:
        - "80:80"
```
